#!/usr/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &  #prüft ob sxhkd läuft und wenn nicht startet es
feh --bg-fill "$HOME/Bilder/Backgrounds/AnnecyFrance.jpg" & #load background image

# Using pywal on bspwm
wal -i $HOME/Bilder/Backgrounds/AnnecyFrance.jpg -s & # falls wal laufen soll
. "${HOME}/.cache/wal/colors.sh"                # source the colors form wal cache

~/.config/polybar/launch.sh --cuts &
xsetroot -cursor_name left_ptr &        # set cursor appearance to "usual one"

# Defining window settings
bspc config border_width            3
bspc config window_gap              8 
bspc config split_ratio             0.52
bspc config borderless_monocle      false
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config top_padding             -4
bspc config bottom_padding          -8 
bspc config left_padding            -8
bspc config right_padding           -8

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"


bspc monitor -d I II III IV V


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium-browser desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
